const adjectives = [
  "Swift",
  "Cosmic",
  "Mystic",
  "Noble",
  "Silent",
  "Brave",
  "Wild",
  "Fierce",
  "Ancient",
  "Stellar",
  "Thunder",
  "Shadow",
  "Crystal",
  "Golden",
  "Silver",
  "Iron",
  "Phantom",
  "Blazing",
  "Frozen",
  "Electric",
  "Mighty",
  "Divine",
  "Rogue",
  "Epic",
  "Legendary",
  "Cryptic",
  "Radiant",
  "Quantum",
  "Neon",
  "Cyber",
  "Digital",
  "Pixel",
  "Lunar",
  "Solar",
  "Astral",
  "Void",
  "Primal",
];

const nouns = [
  "Wolf",
  "Dragon",
  "Phoenix",
  "Tiger",
  "Eagle",
  "Falcon",
  "Lion",
  "Panther",
  "Bear",
  "Hawk",
  "Viper",
  "Raven",
  "Serpent",
  "Fox",
  "Jaguar",
  "Shark",
  "Warrior",
  "Knight",
  "Hunter",
  "Ninja",
  "Samurai",
  "Titan",
  "Guardian",
  "Champion",
  "Legend",
  "Hero",
  "Sage",
  "Wizard",
  "Ranger",
  "Striker",
  "Voyager",
  "Pioneer",
  "Explorer",
  "Sentinel",
  "Crusader",
  "Wanderer",
];

/**
 * Alternative: Generate random name without consistency
 */
export const generateRandomName = (): string => {
  const adjIndex = Math.floor(Math.random() * adjectives.length);
  const nounIndex = Math.floor(Math.random() * nouns.length);
  const number = Math.floor(Math.random() * 1000);

  return `${adjectives[adjIndex]}${nouns[nounIndex]}${number}`;
};
